# -*- coding: utf-8 -*-
"""Audio Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zm6B_nqMeOKW1JtkXzvUegJGsHYkY6Zs
"""

import whisper
from googletrans import Translator
from gtts import gTTS

def translate_audio(input_audio_path, target_languages):
    """
    Transcribes and translates audio to specified languages using Whisper and Google Translate.

    Parameters:
    input_audio_path (str): The path to the input audio file.
    target_languages (list): List of language codes to translate the audio into.

    Returns:
    dict: A dictionary containing the translated texts and their corresponding audio file paths.
    """
    # Load the Whisper model
    medium_model = whisper.load_model("medium.en")

    # Transcribe the audio
    out = medium_model.transcribe(input_audio_path)
    transcribed_text = out['text']

    # Initialize the translator
    translator = Translator()

    # Translate to target languages and save as audio files
    translations = {}
    for lang in target_languages:
        translated_text = translator.translate(transcribed_text, dest=lang).text
        tts = gTTS(translated_text, lang=lang)
        audio_filename = f"translated_{lang}.mp3"
        tts.save(audio_filename)
        translations[lang] = {
            'text': translated_text,
            'audio_path': audio_filename
        }

    return translations