# -*- coding: utf-8 -*-
"""Audio Enhancement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zm6B_nqMeOKW1JtkXzvUegJGsHYkY6Zs
"""

import torch
import torchaudio
from speechbrain.inference.enhancement import SpectralMaskEnhancement
from IPython.display import Audio

def enhance_audio(input_audio_path, output_audio_path):
    """
    Enhances an audio file using the SpectralMaskEnhancement model.

    Parameters:
    input_audio_path (str): The path to the input audio file.
    output_audio_path (str): The path where the enhanced audio will be saved.
    """
    # Initialize the enhancement model
    enhance_model = SpectralMaskEnhancement.from_hparams(
        source="speechbrain/metricgan-plus-voicebank",
        savedir="pretrained_models/metricgan-plus-voicebank",
    )

    # Load and add fake batch dimension
    noisy = enhance_model.load_audio(input_audio_path).unsqueeze(0)

    # Add relative length tensor
    enhanced = enhance_model.enhance_batch(noisy, lengths=torch.tensor([1.]))

    # Saving enhanced signal on disk
    torchaudio.save(output_audio_path, enhanced.cpu(), 16000)

    # Return the path to the enhanced audio file
    return output_audio_path